// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0wXBDrcvnQusQr5hBaDhQzepKPuQ6kNQ',
    appId: '1:871511377693:web:0de665f23eee9ecddac3f4',
    messagingSenderId: '871511377693',
    projectId: 'pomodoro-b6803',
    authDomain: 'pomodoro-b6803.firebaseapp.com',
    storageBucket: 'pomodoro-b6803.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbeekMIrm-sLbopxfQzm9sbtQ51U_8_EE',
    appId: '1:871511377693:android:fe24c7cbf16c2fdfdac3f4',
    messagingSenderId: '871511377693',
    projectId: 'pomodoro-b6803',
    storageBucket: 'pomodoro-b6803.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALZpBODfGXxl4SkRH4rCDXrjZ34DlQ_bQ',
    appId: '1:871511377693:ios:db2762fd7058683adac3f4',
    messagingSenderId: '871511377693',
    projectId: 'pomodoro-b6803',
    storageBucket: 'pomodoro-b6803.appspot.com',
    iosBundleId: 'com.example.todoPomodoroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALZpBODfGXxl4SkRH4rCDXrjZ34DlQ_bQ',
    appId: '1:871511377693:ios:db2762fd7058683adac3f4',
    messagingSenderId: '871511377693',
    projectId: 'pomodoro-b6803',
    storageBucket: 'pomodoro-b6803.appspot.com',
    iosBundleId: 'com.example.todoPomodoroApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0wXBDrcvnQusQr5hBaDhQzepKPuQ6kNQ',
    appId: '1:871511377693:web:49e377f257895d03dac3f4',
    messagingSenderId: '871511377693',
    projectId: 'pomodoro-b6803',
    authDomain: 'pomodoro-b6803.firebaseapp.com',
    storageBucket: 'pomodoro-b6803.appspot.com',
  );
}
